//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlStudio.X.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySqlStudio.X.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked DLL Detected.
        /// </summary>
        internal static string ProgramException_BlockedDllDetected {
            get {
                return ResourceManager.GetString("ProgramException_BlockedDllDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blocked library could not be loaded. You probably downloaded MySQL studio as no-installation zip package. Windows has locked this, preventing so its full operation.
        ///
        ///When you click &quot;OK&quot; MySQL studio will try to automatically unblock all its files. Restart the application for this change to take effect!
        ///
        ///This operation might fail e.g. on read-only volumes or for other reasons. If that is the case then manually unblock the zip package (see its Properties in Explorer) and unzip it again..
        /// </summary>
        internal static string ProgramException_BlockedFiles {
            get {
                return ResourceManager.GetString("ProgramException_BlockedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with one of the system fonts, which indicates this font is corrupt. The original message is:
        ///{0}
        ///MySQL studio needs to close now. You should re-install the font in question to avoid this problem in the future..
        /// </summary>
        internal static string ProgramException_FontProblem {
            get {
                return ResourceManager.GetString("ProgramException_FontProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Font Reported.
        /// </summary>
        internal static string ProgramException_FontProblemDescription {
            get {
                return ResourceManager.GetString("ProgramException_FontProblemDescription", resourceCulture);
            }
        }
    }
}
